ALTER PROCEDURE [dbo].[UVIS_SP_CarTempList_LST_ver3] (
	@GUBUN			CHAR(1),			-- 구분
	@PAGE			INT,				-- 페이지번호
	@ROWS			INT,				-- 목록수

	@SS_OFF_KEY		VARCHAR(9),			-- 로그인 업체키
	@SS_CUST_ID		VARCHAR(14),		-- 로그인 기업ID
	@SS_I_USERID	VARCHAR(50),		-- 로그인 사용자ID
	@SS_I_CODE		CHAR(6),			-- 로그인 권한
	
	@CARGO_YN		CHAR(1) = 'N',		-- 창고여부 (Y=창고, N=차량)
	@START_DATE		VARCHAR(8),			-- 시작일자
	@END_DATE		VARCHAR(8),			-- 종료일자
	@START_TIME		VARCHAR(2),			-- 시간대 시작
	@END_TIME		VARCHAR(2),			-- 시간대 종료

	@P_GRP_ID		VARCHAR(14),		-- 그룹아이디1
	@GRP_ID			VARCHAR(14),		-- 그룹아이디2
	@CM_NUMBER		VARCHAR(30),		-- 차량번호
	@TID_ID         VARCHAR(11),		-- 단말기 번호
	@WORK_GUBUN		CHAR(6) = ''		-- 업무구분
)
AS

DECLARE @SQL NVARCHAR(MAX)

SET NOCOUNT ON

BEGIN
	SET @SQL = ''
	
	BEGIN
		SET @SQL = ' WITH BASEDATA AS (
											SELECT
												BA.*,
												-- A
												ALARM_A.DEVICE_TYPE AS DEVICE_TYPE_A,
												ALARM_A.ISSUE_TEMP_ADJUST AS ISSUE_TEMP_ADJUST_A,
												ALARM_A.ISSUE_PERSIST_TIME AS ISSUE_PERSIST_TIME_A,
												ALARM_A.ISSUE_STEP01_REPEAT AS ISSUE_STEP01_REPEAT_A,
												ALARM_A.ISSUE_STEP01_GROUP AS ISSUE_STEP01_GROUP_A,
												ALARM_A.ISSUE_STEP01_RESTORE AS ISSUE_STEP01_RESTORE_A,
												ALARM_A.ISSUE_STEP02_REPEAT AS ISSUE_STEP02_REPEAT_A,
												ALARM_A.ISSUE_STEP02_GROUP AS ISSUE_STEP02_GROUP_A,
												ALARM_A.ISSUE_STEP02_RESTORE AS ISSUE_STEP02_RESTORE_A,
												TIME_A.ALARM_TIME_A,
												-- B
												ALARM_B.DEVICE_TYPE AS DEVICE_TYPE_B,
												ALARM_B.ISSUE_TEMP_ADJUST AS ISSUE_TEMP_ADJUST_B,
												ALARM_B.ISSUE_PERSIST_TIME AS ISSUE_PERSIST_TIME_B,
												ALARM_B.ISSUE_STEP01_REPEAT AS ISSUE_STEP01_REPEAT_B,
												ALARM_B.ISSUE_STEP01_GROUP AS ISSUE_STEP01_GROUP_B,
												ALARM_B.ISSUE_STEP01_RESTORE AS ISSUE_STEP01_RESTORE_B,
												ALARM_B.ISSUE_STEP02_REPEAT AS ISSUE_STEP02_REPEAT_B,
												ALARM_B.ISSUE_STEP02_GROUP AS ISSUE_STEP02_GROUP_B,
												ALARM_B.ISSUE_STEP02_RESTORE AS ISSUE_STEP02_RESTORE_B,
												TIME_B.ALARM_TIME_B,
												-- C
												ALARM_C.DEVICE_TYPE AS DEVICE_TYPE_C,
												ALARM_C.ISSUE_TEMP_ADJUST AS ISSUE_TEMP_ADJUST_C,
												ALARM_C.ISSUE_PERSIST_TIME AS ISSUE_PERSIST_TIME_C,
												ALARM_C.ISSUE_STEP01_REPEAT AS ISSUE_STEP01_REPEAT_C,
												ALARM_C.ISSUE_STEP01_GROUP AS ISSUE_STEP01_GROUP_C,
												ALARM_C.ISSUE_STEP01_RESTORE AS ISSUE_STEP01_RESTORE_C,
												ALARM_C.ISSUE_STEP02_REPEAT AS ISSUE_STEP02_REPEAT_C,
												ALARM_C.ISSUE_STEP02_GROUP AS ISSUE_STEP02_GROUP_C,
												ALARM_C.ISSUE_STEP02_RESTORE AS ISSUE_STEP02_RESTORE_C,
												TIME_C.ALARM_TIME_C,
												-- D
												ALARM_D.DEVICE_TYPE AS DEVICE_TYPE_D,
												ALARM_D.ISSUE_TEMP_ADJUST AS ISSUE_TEMP_ADJUST_D,
												ALARM_D.ISSUE_PERSIST_TIME AS ISSUE_PERSIST_TIME_D,
												ALARM_D.ISSUE_STEP01_REPEAT AS ISSUE_STEP01_REPEAT_D,
												ALARM_D.ISSUE_STEP01_GROUP AS ISSUE_STEP01_GROUP_D,
												ALARM_D.ISSUE_STEP01_RESTORE AS ISSUE_STEP01_RESTORE_D,
												ALARM_D.ISSUE_STEP02_REPEAT AS ISSUE_STEP02_REPEAT_D,
												ALARM_D.ISSUE_STEP02_GROUP AS ISSUE_STEP02_GROUP_D,
												ALARM_D.ISSUE_STEP02_RESTORE AS ISSUE_STEP02_RESTORE_D,
												TIME_D.ALARM_TIME_D
											FROM
												(
													SELECT
														CONVERT(INT, ROW_NUMBER() OVER( ORDER BY ISNULL(P_GRP_ID, ''Z0000000000000'') DESC, P_GRP_NAME, GRP_NAME, OFF_NAME, CM_NUMBER)) RNUM,
														P_GRP_ID,
														P_GRP_NAME,
														GRP_ID,
														GRP_NAME,
														BA.OFF_NAME,
														BA.OFF_KEY,
														WORK_GUBUN AS WORK_GUBUN_CODE,
														N_CODENAME AS WORK_GUBUN_NAME,
														CM_KEY,
														CM_NUMBER,
														BA.TID_ID,
														TEMP_MIN_A, TEMP_MAX_A, TEMP_MIN_B, TEMP_MAX_B, TEMP_MIN_C, TEMP_MAX_C, TEMP_MIN_D, TEMP_MAX_D,
														MAX(ISNULL(BA.TOT_CNT, 0)) AS TOT_CNT,
														MAX(ISNULL(BA.ISSUE_CNT, 0)) AS ISSUE_CNT
													FROM (
														SELECT
															ISNULL(L1.P_GRP_ID, ''00000000000000'') AS P_GRP_ID,		-- 상위그룹
															ISNULL(L1.P_GRP_NAME, ''그룹미지정'') AS P_GRP_NAME, 		-- 상위그룹명
															ISNULL(L1.GRP_ID, ''00000000000000'') AS GRP_ID,		    -- 그룹
															ISNULL(L1.GRP_NAME, ''그룹미지정'') AS GRP_NAME,	        -- 그룹명
															TID.OFF_KEY,
															OT.OFF_NAME,
															TID.TID_ID,
															CT.CM_KEY,
															CT.CM_NUMBER,
															CT.WORK_GUBUN,
															CODE.N_CODENAME,
															-- A
															TEMP_A.TEMP_MIN AS TEMP_MIN_A,
															TEMP_A.TEMP_MAX AS TEMP_MAX_A,
															-- B
															TEMP_B.TEMP_MIN AS TEMP_MIN_B,
															TEMP_B.TEMP_MAX AS TEMP_MAX_B,
															-- C
															TEMP_C.TEMP_MIN AS TEMP_MIN_C,
															TEMP_C.TEMP_MAX AS TEMP_MAX_C,
															-- D
															TEMP_D.TEMP_MIN AS TEMP_MIN_D,
															TEMP_D.TEMP_MAX AS TEMP_MAX_D,
															ISNULL(TEM_AGG.TOT_CNT, 0) AS TOT_CNT,
															ISNULL(TEM_AGG.ISSUE_CNT, 0) AS ISSUE_CNT
														FROM Vehicle_System.dbo.TERMINALIDTBL TID WITH(NOLOCK)      -- 단말기 정보
														INNER JOIN Vehicle_System.dbo.CustomerOfficeRel COR WITH(nolock)	-- 관계 업체정보
															ON COR.OFF_KEY = TID.OFF_KEY
															AND COR.DEL_YN = ''N''
														LEFT OUTER JOIN Vehicle_System.dbo.CARMASTERTBL CT WITH(NOLOCK)  -- 차량정보
															ON CT.OFF_KEY = TID.OFF_KEY
															AND CT.TID_ID = TID.TID_ID
															AND CT.CM_DEL_FLAG = ''1''
														LEFT OUTER JOIN Vehicle_System.dbo.UVIS_TB_GROUP_CAR UTGC WITH(NOLOCK)	 -- 그룹 차량
															ON UTGC.CUST_ID = COR.CUST_ID
															AND UTGC.OFF_KEY = COR.OFF_KEY
															AND UTGC.CM_KEY = CT.CM_KEY
															AND UTGC.USE_YN = ''Y''
														LEFT OUTER JOIN Vehicle_System.dbo.UVIS_TB_GROUP_USER UTGU WITH(NOLOCK)  -- 그룹 사용자
															ON UTGU.CUST_ID = UTGC.CUST_ID
															AND UTGU.GRP_ID = UTGC.GRP_ID
															AND UTGU.OFF_KEY = UTGC.OFF_KEY
														LEFT OUTER JOIN Vehicle_System.dbo.UVIS_VW_GROUP L1 WITH(NOLOCK)	      -- 그룹정보
															ON L1.CUST_ID = UTGU.CUST_ID
															AND L1.GRP_ID = UTGU.GRP_ID
														LEFT OUTER JOIN Vehicle_System.dbo.OFFICETBL OT WITH(NOLOCK)
															ON CT.OFF_KEY = OT.OFF_KEY
														LEFT OUTER JOIN Vehicle_System.dbo.DRIVERTBL DT WITH(NOLOCK)
															ON CT.OFF_KEY = DT.OFF_KEY
															AND CT.DRI_IDX = DT.DRI_IDX
														LEFT OUTER JOIN Vehicle_System.dbo.COMMONCODETBL_KR CODE WITH(NOLOCK)
															ON I_ROOT = ''506''
															AND I_ORDER > 0
															AND CT.WORK_GUBUN = CODE.I_CODE
															LEFT OUTER JOIN  VEHICLE_SYSTEM.dbo.TemperatureConfigTBL AS TEMP_A WITH(NOLOCK) 
																ON CT.OFF_KEY = TEMP_A.OFF_KEY
																AND CT.TID_ID = TEMP_A.TID_ID
															AND TEMP_A.DEVICE_NUM = ''A''
														LEFT OUTER JOIN VEHICLE_SYSTEM.dbo.TemperatureConfigTBL AS TEMP_B WITH(NOLOCK) 
															ON CT.OFF_KEY = TEMP_B.OFF_KEY
															AND CT.TID_ID = TEMP_B.TID_ID
															AND TEMP_B.DEVICE_NUM = ''B''
														LEFT OUTER JOIN  VEHICLE_SYSTEM.dbo.TemperatureConfigTBL AS TEMP_C WITH(NOLOCK) 
															ON CT.OFF_KEY = TEMP_C.OFF_KEY
															AND CT.TID_ID = TEMP_C.TID_ID
															AND TEMP_C.DEVICE_NUM = ''C''
															LEFT OUTER JOIN  VEHICLE_SYSTEM.dbo.TemperatureConfigTBL AS TEMP_D WITH(NOLOCK) 
																ON CT.OFF_KEY = TEMP_D.OFF_KEY
																AND CT.TID_ID = TEMP_D.TID_ID
																AND TEMP_D.DEVICE_NUM = ''D''
															OUTER APPLY (
																SELECT
																	COUNT_BIG(1) AS TOT_CNT,
																	SUM(TEM_CALC.ISSUE_FLAG) AS ISSUE_CNT
																FROM (
																	SELECT
																		CASE
																			WHEN
																				(CALC.TEMPER_A IS NOT NULL AND (CALC.TEMPER_A > ISNULL(TEMP_A.TEMP_MAX, 0) OR CALC.TEMPER_A < ISNULL(TEMP_A.TEMP_MIN, 0)))
																				OR (CALC.TEMPER_B IS NOT NULL AND (CALC.TEMPER_B > ISNULL(TEMP_B.TEMP_MAX, 0) OR CALC.TEMPER_B < ISNULL(TEMP_B.TEMP_MIN, 0)))
																				OR (CALC.TEMPER_C IS NOT NULL AND (CALC.TEMPER_C > ISNULL(TEMP_C.TEMP_MAX, 0) OR CALC.TEMPER_C < ISNULL(TEMP_C.TEMP_MIN, 0)))
																				OR (CALC.TEMPER_D IS NOT NULL AND (CALC.TEMPER_D > ISNULL(TEMP_D.TEMP_MAX, 0) OR CALC.TEMPER_D < ISNULL(TEMP_D.TEMP_MIN, 0)))
																			THEN 1
																			ELSE 0
																		END AS ISSUE_FLAG
																	FROM DBO.TEMPERATURETBL TEM WITH(NOLOCK) --2022.08 BK09로 백업정책 전환
																	CROSS APPLY (
																		SELECT
																			CASE
																				WHEN SUBSTRING(TEM.TPL_DEGREE_A, 1, 1) IN (''N'', ''S'', ''O'') THEN NULL
																				WHEN TEM.TPL_SIGNAL_A = 1 THEN -ABS(TRY_CONVERT(FLOAT, TEM.TPL_DEGREE_A))
																				ELSE TRY_CONVERT(FLOAT, TEM.TPL_DEGREE_A)
																			END AS TEMPER_A,
																			CASE
																				WHEN SUBSTRING(TEM.TPL_DEGREE_B, 1, 1) IN (''N'', ''S'', ''O'') THEN NULL
																				WHEN TEM.TPL_SIGNAL_B = 1 THEN -ABS(TRY_CONVERT(FLOAT, TEM.TPL_DEGREE_B))
																				ELSE TRY_CONVERT(FLOAT, TEM.TPL_DEGREE_B)
																			END AS TEMPER_B,
																			CASE
																				WHEN SUBSTRING(TEM.TPL_DEGREE_C, 1, 1) IN (''N'', ''S'', ''O'') THEN NULL
																				WHEN TEM.TPL_SIGNAL_C = 1 THEN -ABS(TRY_CONVERT(FLOAT, TEM.TPL_DEGREE_C))
																				ELSE TRY_CONVERT(FLOAT, TEM.TPL_DEGREE_C)
																			END AS TEMPER_C,
																			CASE
																				WHEN SUBSTRING(TEM.TPL_DEGREE_D, 1, 1) IN (''N'', ''S'', ''O'') THEN NULL
																				WHEN TEM.TPL_SIGNAL_D = 1 THEN -ABS(TRY_CONVERT(FLOAT, TEM.TPL_DEGREE_D))
																				ELSE TRY_CONVERT(FLOAT, TEM.TPL_DEGREE_D)
																			END AS TEMPER_D
																	) CALC
																	WHERE TID.OFF_KEY = TEM.OFF_KEY
																	AND TID.TID_ID = TEM.TID_ID
																	AND TEM.TPL_DATE BETWEEN ''' + @START_DATE + ''' AND ''' + @END_DATE + '''
																	AND TEM.TPL_DATE + TEM.TPL_TIME BETWEEN ''' + @START_DATE + @START_TIME + '0000'' AND ''' + @END_DATE + @END_TIME + '0001''
																) TEM_CALC
															) TEM_AGG
															WHERE (CT.CM_KEY IS NOT NULL OR CT.CM_KEY <> '''')
														AND TID.TID_USE_FLAG = ''1''
														--AND TEM.TPL_DATE BETWEEN '''+@START_DATE+'''  AND '''+@END_DATE+'''
														--AND TEM.TPL_DATE + TEM.TPL_TIME BETWEEN '''+@START_DATE+@START_TIME+'0000''  AND '''+@END_DATE+@END_TIME+'0001''
														--AND TEM.TPL_DATE BETWEEN '''+@START_DATE+'''  AND '''+@END_DATE+'''
														--AND TEM.TPL_TIME BETWEEN ''' + @START_TIME + ''' + ''0000'' AND ''' + @END_TIME + ''' + ''0001''
														-- 사용자그룹의 차량만 표시 (관리자는 그룹미등록 차량까지 표시)
														AND (
															UTGU.I_USERID = ''' + @SS_I_USERID + '''
															OR (
																''' + @SS_I_CODE + ''' = ''999022''
																AND UTGU.I_USERID IS NULL
															)
														)
														AND CT.OFF_KEY = '''+@SS_OFF_KEY+''' '
		
		-- 창고
		IF @CARGO_YN = 'Y'
			BEGIN
				SET @SQL = @SQL + '						AND CT.CM_CLASS = ''128012'' '
			END
		-- 차량
		ELSE
			BEGIN
				SET @SQL = @SQL + '						AND ISNULL(CT.CM_CLASS,'''') != ''128012'' '
			END

		-- 그룹1 검색
		IF @P_GRP_ID IS NOT NULL AND @P_GRP_ID <> ''
			BEGIN
				IF @P_GRP_ID = '00000000000000'
					BEGIN
						SET @SQL = @SQL + '				AND (L1.P_GRP_ID IS NULL OR L1.P_GRP_ID = '''') '
					END
				ELSE
					BEGIN
						SET @SQL = @SQL + '				AND L1.P_GRP_ID = ''' + @P_GRP_ID + ''' '
					END
			END
		
		-- 그룹2 검색
		IF @GRP_ID IS NOT NULL AND @GRP_ID <> ''
			BEGIN
				SET @SQL = @SQL + '						AND UTGU.GRP_ID = ''' + @GRP_ID + ''' '
			END
		
		-- 차량번호 검색
		IF @CM_NUMBER IS NOT NULL AND @CM_NUMBER <> ''
			BEGIN
				SET @SQL = @SQL + '						AND CT.CM_NUMBER LIKE ''%' + @CM_NUMBER + '%'' '
			END

		-- 단말기번호 검색
		IF @TID_ID IS NOT NULL AND @TID_ID <> ''
			BEGIN
				SET @SQL = @SQL + '						AND CT.TID_ID LIKE ''%' + @TID_ID + '%'' '
			END
		
		-- 업무구분 검색
		IF @WORK_GUBUN IS NOT NULL AND @WORK_GUBUN <> ''
			BEGIN
				SET @SQL = @SQL + '						AND CT.WORK_GUBUN = ''' + @WORK_GUBUN + ''' '
			END

		SET @SQL = @SQL + '							) BA
												WHERE 1=1 
												GROUP BY P_GRP_ID, P_GRP_NAME, GRP_ID, GRP_NAME, OFF_NAME, OFF_KEY, WORK_GUBUN, N_CODENAME, CM_KEY, CM_NUMBER, TID_ID, TEMP_MIN_A, TEMP_MAX_A, TEMP_MIN_B, TEMP_MAX_B, TEMP_MIN_C, TEMP_MAX_C, TEMP_MIN_D, TEMP_MAX_D
											) BA
											LEFT OUTER JOIN Vehicle_System.dbo.TemperatureAlarmConfigTBL AS ALARM_A WITH(NOLOCK) 
												ON BA.OFF_KEY = ALARM_A.OFF_KEY
												AND BA.TID_ID = ALARM_A.TID_ID
												AND ALARM_A.DEVICE_NUM = ''A'' '
		SET @SQL = @SQL + '					OUTER APPLY (
												SELECT
													MAX(CASE WHEN SORT_NUMBER = 1 THEN (CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 2 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 3 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 4 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 5 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 6 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 7 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 8 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 9 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 10 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END)
													AS ALARM_TIME_A
												FROM (
													SELECT
														ROW_NUMBER() OVER(PARTITION BY OFF_KEY, TID_ID, DEVICE_NUM ORDER BY ALARM_NUM) AS SORT_NUMBER,
														TIME_A.*
													FROM Vehicle_System.dbo.TemperatureAlarmTimeTBL TIME_A WITH(NOLOCK) 
													WHERE 1=1
													AND TIME_A.OFF_KEY = ALARM_A.OFF_KEY
													AND TIME_A.TID_ID = ALARM_A.TID_ID
													AND TIME_A.DEVICE_NUM = ALARM_A.DEVICE_NUM
												) TIME_A
												GROUP BY TIME_A.OFF_KEY, TIME_A.TID_ID, TIME_A.DEVICE_NUM
											) TIME_A '
		SET @SQL = @SQL + '					LEFT OUTER JOIN Vehicle_System.dbo.TemperatureAlarmConfigTBL AS ALARM_B WITH(NOLOCK) 
												ON BA.OFF_KEY = ALARM_B.OFF_KEY
												AND BA.TID_ID = ALARM_B.TID_ID
												AND ALARM_B.DEVICE_NUM = ''B'' '
		SET @SQL = @SQL + '					OUTER APPLY (
												SELECT
													MAX(CASE WHEN SORT_NUMBER = 1 THEN (CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 2 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 3 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 4 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 5 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 6 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 7 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 8 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 9 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 10 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END)
													AS ALARM_TIME_B
												FROM (
													SELECT
														ROW_NUMBER() OVER(PARTITION BY OFF_KEY, TID_ID, DEVICE_NUM ORDER BY ALARM_NUM) AS SORT_NUMBER,
														TIME_B.*
													FROM Vehicle_System.dbo.TemperatureAlarmTimeTBL TIME_B WITH(NOLOCK) 
													WHERE 1=1
													AND TIME_B.OFF_KEY = ALARM_B.OFF_KEY
													AND TIME_B.TID_ID = ALARM_B.TID_ID
													AND TIME_B.DEVICE_NUM = ALARM_B.DEVICE_NUM
												) TIME_B
												GROUP BY TIME_B.OFF_KEY, TIME_B.TID_ID, TIME_B.DEVICE_NUM
											) TIME_B '
		SET @SQL = @SQL + '					LEFT OUTER JOIN Vehicle_System.dbo.TemperatureAlarmConfigTBL AS ALARM_C WITH(NOLOCK) 
												ON BA.OFF_KEY = ALARM_C.OFF_KEY
												AND BA.TID_ID = ALARM_C.TID_ID
												AND ALARM_C.DEVICE_NUM = ''C'' '
		SET @SQL = @SQL + '					OUTER APPLY (
												SELECT
													MAX(CASE WHEN SORT_NUMBER = 1 THEN (CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 2 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 3 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 4 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 5 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 6 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 7 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 8 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 9 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 10 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END)
													AS ALARM_TIME_C
												FROM (
													SELECT
														ROW_NUMBER() OVER(PARTITION BY OFF_KEY, TID_ID, DEVICE_NUM ORDER BY ALARM_NUM) AS SORT_NUMBER,
														TIME_C.*
													FROM Vehicle_System.dbo.TemperatureAlarmTimeTBL TIME_C WITH(NOLOCK) 
													WHERE 1=1
													AND TIME_C.OFF_KEY = ALARM_C.OFF_KEY
													AND TIME_C.TID_ID = ALARM_C.TID_ID
													AND TIME_C.DEVICE_NUM = ALARM_C.DEVICE_NUM
												) TIME_C
												GROUP BY TIME_C.OFF_KEY, TIME_C.TID_ID, TIME_C.DEVICE_NUM
											) TIME_C '
		SET @SQL = @SQL + '					LEFT OUTER JOIN Vehicle_System.dbo.TemperatureAlarmConfigTBL AS ALARM_D WITH(NOLOCK) 
												ON BA.OFF_KEY = ALARM_D.OFF_KEY
												AND BA.TID_ID = ALARM_D.TID_ID
												AND ALARM_D.DEVICE_NUM = ''D'' '
		SET @SQL = @SQL + '					OUTER APPLY (
												SELECT
													MAX(CASE WHEN SORT_NUMBER = 1 THEN (CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 2 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 3 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 4 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 5 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 6 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 7 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 8 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 9 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END) '
		SET @SQL = @SQL + '							+ MAX(CASE WHEN SORT_NUMBER = 10 THEN ('';'' + CASE WHEN ALARM_SUNDAY = ''Y'' THEN ''1'' ELSE '''' END + CASE WHEN ALARM_MONDAY = ''Y'' THEN ''2'' ELSE '''' END + CASE WHEN ALARM_TUESDAY = ''Y'' THEN ''3'' ELSE '''' END + CASE WHEN ALARM_WEDNESDAY = ''Y'' THEN ''4'' ELSE '''' END + CASE WHEN ALARM_THURSDAY = ''Y'' THEN ''5'' ELSE '''' END + CASE WHEN ALARM_FRIDAY = ''Y'' THEN ''6'' ELSE '''' END + CASE WHEN ALARM_SATURDAY = ''Y'' THEN ''7'' ELSE '''' END + '':'' + ALARM_START + ''~'' + ALARM_END) ELSE '''' END)
													AS ALARM_TIME_D
												FROM (
													SELECT
														ROW_NUMBER() OVER(PARTITION BY OFF_KEY, TID_ID, DEVICE_NUM ORDER BY ALARM_NUM) AS SORT_NUMBER,
														TIME_D.*
													FROM Vehicle_System.dbo.TemperatureAlarmTimeTBL TIME_D WITH(NOLOCK) 
													WHERE 1=1
													AND TIME_D.OFF_KEY = ALARM_D.OFF_KEY
													AND TIME_D.TID_ID = ALARM_D.TID_ID
													AND TIME_D.DEVICE_NUM = ALARM_D.DEVICE_NUM
												) TIME_D
												GROUP BY TIME_D.OFF_KEY, TIME_D.TID_ID, TIME_D.DEVICE_NUM
											) TIME_D '
		SET @SQL = @SQL + '				) '
	END

	-- 전체
	IF @GUBUN = 3
		BEGIN
			SET @SQL = @SQL + '
								SELECT
									A.*
									, CASE WHEN ISSUE_CNT > 0 THEN ''Y'' ELSE ''N'' END AS DTG_SENSING 
									, CASE WHEN LEN(A.TID_ID) > 4 THEN ''Y'' ELSE ''N'' END AS DTG_DEVICE
									-- TEMP
									, CUR.TPL_SIGNAL_A, CUR.TPL_DEGREE_A
									, CUR.TPL_SIGNAL_B, CUR.TPL_DEGREE_B
									, CUR.TPL_SIGNAL_C, CUR.TPL_DEGREE_C
									, CUR.TPL_SIGNAL_D, CUR.TPL_DEGREE_D
									, CASE
										WHEN SUBSTRING(CUR.TPL_DEGREE_A,1,1) IN (''N'', ''S'', ''O'') OR CUR.TPL_DEGREE_A IS NULL THEN NULL
										ELSE 
											CASE WHEN CUR.TPL_SIGNAL_A=1 THEN -ABS(CUR.TPL_DEGREE_A)
											ELSE CUR.TPL_DEGREE_A END 
										END AS TEMPER_A
									, CASE WHEN SUBSTRING(CUR.TPL_DEGREE_B,1,1) IN (''N'', ''S'', ''O'') OR CUR.TPL_DEGREE_B IS NULL THEN NULL
										ELSE
											CASE WHEN CUR.TPL_SIGNAL_B=1 THEN -ABS(CUR.TPL_DEGREE_B)
											ELSE CUR.TPL_DEGREE_B END 
										END AS TEMPER_B
									, CASE WHEN SUBSTRING(CUR.TPL_DEGREE_C,1,1) IN (''N'', ''S'', ''O'') OR CUR.TPL_DEGREE_C IS NULL THEN NULL
										ELSE
											CASE WHEN CUR.TPL_SIGNAL_C=1 THEN -ABS(CUR.TPL_DEGREE_C)
											ELSE CUR.TPL_DEGREE_C END 
										END AS TEMPER_C
									, CASE WHEN SUBSTRING(CUR.TPL_DEGREE_D,1,1) IN (''N'', ''S'', ''O'') OR CUR.TPL_DEGREE_D IS NULL THEN NULL
										ELSE
											CASE WHEN CUR.TPL_SIGNAL_D=1 THEN -ABS(CUR.TPL_DEGREE_D)
											ELSE CUR.TPL_DEGREE_D END 
										END AS TEMPER_D

								FROM BASEDATA A 
								outer APPLY (
									SELECT TOP 1 *
									  FROM DBO.TEMPERATURETBL TEM WITH(NOLOCK)		--2022.08 BK09로 백업정책 전환												
									WHERE OFF_KEY = A.OFF_KEY
									AND TID_ID = A.TID_ID
									ORDER BY TPL_DATE DESC, TPL_TIME DESC
								) CUR
								ORDER BY ISNULL(P_GRP_ID, ''Z0000000000000'') DESC, P_GRP_NAME, GRP_NAME,OFF_NAME, CM_NUMBER
								--, ISSUE_CNT
								'
		END
	
	-- 카운트
	ELSE IF @GUBUN = 2
		BEGIN
			SET @SQL = @SQL + '
								SELECT
									COUNT(*) AS TOT_COUNT, 
									SUM(CASE WHEN ISSUE_CNT > 0 THEN 1 ELSE 0 END) AS ERR_COUNT 
								FROM BASEDATA A WITH(NOLOCK) '
		END
	
	-- 페이징
	ELSE IF @GUBUN = 1
		BEGIN
			SET @SQL = @SQL + '
								SELECT
									A.*
									, CASE WHEN ISSUE_CNT > 0 THEN ''Y'' ELSE ''N'' END AS DTG_SENSING 
									, CASE WHEN LEN(A.TID_ID) > 4 THEN ''Y'' ELSE ''N'' END AS DTG_DEVICE
									-- TEMP
									, CUR.TPL_SIGNAL_A, CUR.TPL_DEGREE_A
									, CUR.TPL_SIGNAL_B, CUR.TPL_DEGREE_B
									, CUR.TPL_SIGNAL_C, CUR.TPL_DEGREE_C
									, CUR.TPL_SIGNAL_D, CUR.TPL_DEGREE_D
									, CASE
										WHEN SUBSTRING(CUR.TPL_DEGREE_A,1,1) IN (''N'', ''S'', ''O'') OR CUR.TPL_DEGREE_A IS NULL THEN NULL
										ELSE 
											CASE WHEN CUR.TPL_SIGNAL_A=1 THEN -ABS(CUR.TPL_DEGREE_A)
											ELSE CUR.TPL_DEGREE_A END 
										END AS TEMPER_A
									, CASE WHEN SUBSTRING(CUR.TPL_DEGREE_B,1,1) IN (''N'', ''S'', ''O'') OR CUR.TPL_DEGREE_B IS NULL THEN NULL
										ELSE
											CASE WHEN CUR.TPL_SIGNAL_B=1 THEN -ABS(CUR.TPL_DEGREE_B)
											ELSE CUR.TPL_DEGREE_B END 
										END AS TEMPER_B
									, CASE WHEN SUBSTRING(CUR.TPL_DEGREE_C,1,1) IN (''N'', ''S'', ''O'') OR CUR.TPL_DEGREE_C IS NULL THEN NULL
										ELSE
											CASE WHEN CUR.TPL_SIGNAL_C=1 THEN -ABS(CUR.TPL_DEGREE_C)
											ELSE CUR.TPL_DEGREE_C END 
										END AS TEMPER_C
									, CASE WHEN SUBSTRING(CUR.TPL_DEGREE_D,1,1) IN (''N'', ''S'', ''O'') OR CUR.TPL_DEGREE_D IS NULL THEN NULL
										ELSE
											CASE WHEN CUR.TPL_SIGNAL_D=1 THEN -ABS(CUR.TPL_DEGREE_D)
											ELSE CUR.TPL_DEGREE_D END 
										END AS TEMPER_D

								FROM BASEDATA A WITH(NOLOCK)
								outer APPLY (
									SELECT TOP 1 *
									--FROM DBO.TEMPERATURETBL WITH(NOLOCK)
									FROM DBO.TEMPERATURETBL WITH(NOLOCK) --2022.08 BK09로 백업정책 전환
									WHERE OFF_KEY = A.OFF_KEY
									AND TID_ID = A.TID_ID
									ORDER BY TPL_DATE DESC, TPL_TIME DESC
								) CUR

								ORDER BY ISNULL(P_GRP_ID, ''Z0000000000000'') DESC, P_GRP_NAME, GRP_NAME, OFF_NAME, CM_NUMBER
								--, ISSUE_CNT
								OFFSET (' + CONVERT(VARCHAR, @ROWS) + ' * ' + CONVERT(VARCHAR, @PAGE) + ') - ' + CONVERT(VARCHAR, @ROWS) + ' ROWS
								FETCH NEXT ' + CONVERT(VARCHAR, @ROWS) + ' ROW ONLY
								'
		END

	exec master.dbo.sp_print @SQL
	EXEC SP_EXECUTESQL @SQL
END
